<a href="https://colab.research.google.com/github/vedasri2511/DL-153/blob/main/DL_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* dl deals with non linear data(curve)
* more pixels more acc
* automatic feature extraction
* interpretation is difficult
* uses graphical and tensor processing unit
* data, model selection(no model which is perfect depends on parameters)
* so selecting model it is noted that which metric is imp for which type of prob like for imbalance f1 score (its harmonic mean of per and recall)
* we use keras its easy for quick speed similar to tf, tf for ml and dl for neural network and video kind of data, pytorch for nlp, cntk frameworks
* to conclude we use keras
* derivation of error is gradient
* sequential means feed forward nn
* verbose is enabled to see op in each iteration
* g is agg and f is activation function
* steps of perceptron: it takes input, it sums, it up checks the ip and gives the op
* bias acts as a decision boundary and adds non linearity(when all ip becomes 0 then bias helps to make the decision)
* fired: op is 1(when bias is increased)
* step gives 0 or 1 and sigmoid gives prob value
* for ip we use data point as term
* dp can be separable for and and or op but not for xor(same same unte 0)(cant be divided using a single line. for and and or 3 are one side and one dp is on another side so they are separable)
*



In [ ]:
#Implement AND and OR logic operations using a single perceptron, and verify the correctness of the output using appropriate truth tables. (linear Data)
import numpy as np
def step(x):
  return 1 if x>=0 else 0
class perceptron:
  def __init__(self,w,b):
    self.w=w
    self.b=b
  def predict(self,inputs):
    total=np.dot(self.w,inputs)+self.b
    return step(total)
w=np.array([1,1])
b=-1.5
and_op=perceptron(w,b)
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(x,"->",and_op.predict(np.array(x)))

(0, 0) -> 0
(0, 1) -> 0
(1, 0) -> 0
(1, 1) -> 1


In [ ]:
#or
import numpy as np
def step(x):
  return 1 if x>=0 else 0
class per:
  def __init__(self,w,b):
    self.w=w
    self.b=b
  def predict(self,inp):
    t=np.dot(self.w,inp)+self.b
    return step(t)
w=np.array([1,1])
b=-0.5
or_op=per(w,b)
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(x,"->",or_op.predict(np.array(x)))


(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 1


In [ ]:
#xor
import numpy as np
def step(x):
  return 1 if x>=0 else 0
class per:
  def __init__(self,w,b):
    self.w=w
    self.b=b
  def predict(self,inp):
    t=np.dot(self.w,inp)+self.b
    return step(t)
w=np.array([1,1])
b=-0.5
or_op=per(w,b)
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(x,"->",or_op.predict(np.array(x)))

(0, 0) -> 0
(0, 1) -> 1
(1, 0) -> 1
(1, 1) -> 1


In [ ]:
#xnor gate
def step(x):
    if x > 0:
        return 1
    else:
        return 0
def not_gate(x):
    return 0 if x == 1 else 1
def neuron(x1, x2, w1, w2, b):
    net = (x1 * w1) + (x2 * w2) + b
    return step(net)
def xor_gate(A, B):
    h1 = neuron(A, B, w1=1, w2=1, b=0)
    h2 = neuron(A, B, w1=-1, w2=-1, b=2)
    y = neuron(h1, h2, w1=1, w2=1, b=-1)
    return y
# XNOR = NOT(XOR)
def xnor_gate(A, B):
    xor_out = xor_gate(A, B)
    return not_gate(xor_out)

if __name__ == "__main__":
    print("A B | XOR XNOR")
    test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
    for A, B in test_inputs:
        print(f"{A} {B} |  {xor_gate(A, B)}    {xnor_gate(A, B)}")

A B | XOR XNOR
0 0 |  0    1
0 1 |  1    0
1 0 |  1    0
1 1 |  0    1


In [ ]:
#5
def step(x):
    return 1 if x >= 0 else 0
X = [
    [1, 1, 0, 0.9],   # like
    [0, 1, 1, 0.85],  # like
    [1, 0, 0, 0.6],   # like
    [0, 0, 0, 0.4],   # dislike
    [0, 1, 0, 0.45],  # dislike
    [1, 0, 1, 0.95]   # like
]

y = [1, 1, 1, 0, 0, 1]  # labels


# Initialize weights and bias
weights = [0, 0, 0, 0]
bias = 0
learning_rate = 0.1
epochs = 5


# Perceptron training
for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    for i in range(len(X)):
        net = sum(X[i][j] * weights[j] for j in range(4)) + bias
        prediction = step(net)
        error = y[i] - prediction

        # Update weights and bias
        for j in range(4):
            weights[j] += learning_rate * error * X[i][j]
        bias += learning_rate * error

        print("Weights:", weights, "Bias:", bias)



Epoch 1
Weights: [0.0, 0.0, 0.0, 0.0] Bias: 0.0
Weights: [0.0, 0.0, 0.0, 0.0] Bias: 0.0
Weights: [0.0, 0.0, 0.0, 0.0] Bias: 0.0
Weights: [0.0, 0.0, 0.0, -0.04000000000000001] Bias: -0.1
Weights: [0.0, 0.0, 0.0, -0.04000000000000001] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.05499999999999999] Bias: 0.0

Epoch 2
Weights: [0.1, 0.0, 0.1, 0.05499999999999999] Bias: 0.0
Weights: [0.1, 0.0, 0.1, 0.05499999999999999] Bias: 0.0
Weights: [0.1, 0.0, 0.1, 0.05499999999999999] Bias: 0.0
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1

Epoch 3
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bias: -0.1
Weights: [0.1, 0.0, 0.1, 0.014999999999999986] Bi

In [ ]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Movie features: [Matt Damon, Thriller, Nolan, IMDb rating]
X = np.array([
    [1, 1, 0, 0.85],
    [0, 1, 1, 0.90],
    [1, 0, 0, 0.60],
    [0, 0, 0, 0.40],
    [0, 1, 0, 0.45],
    [1, 0, 1, 0.95],
    [0, 0, 1, 0.50],
    [1, 1, 1, 0.92]
])

# Output labels
y = np.array([
    [1],
    [1],
    [1],
    [0],
    [0],
    [1],
    [0],
    [1]
])


# ---------------- INITIALIZATION ----------------
np.random.seed(42)

W1 = np.random.rand(4, 3)    # Input → Hidden (4 features, 3 neurons)
b1 = np.random.rand(1, 3)

W2 = np.random.rand(3, 1)    # Hidden → Output
b2 = np.random.rand(1, 1)

learning_rate = 0.1
epochs = 5000


# ---------------- TRAINING ----------------
for epoch in range(epochs):

    # Forward propagation
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    y_pred = sigmoid(final_input)

    # Loss (Mean Squared Error)
    error = y - y_pred
    loss = np.mean(error ** 2)

    # Backpropagation
    d_output = error * sigmoid_derivative(y_pred)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(hidden_output)

    # Update weights and biases
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")
print("\nMovie Preference Prediction:")
for i in range(len(X)):
    decision = "GO " if y_pred[i][0] >= 1 else "NOT GO "
    print(X[i], "->", decision)


Epoch 0, Loss: 0.2434
Epoch 1000, Loss: 0.0136
Epoch 2000, Loss: 0.0039
Epoch 3000, Loss: 0.0020
Epoch 4000, Loss: 0.0013

Movie Preference Prediction:
[1.   1.   0.   0.85] -> NOT GO 
[0.  1.  1.  0.9] -> NOT GO 
[1.  0.  0.  0.6] -> NOT GO 
[0.  0.  0.  0.4] -> NOT GO 
[0.   1.   0.   0.45] -> NOT GO 
[1.   0.   1.   0.95] -> NOT GO 
[0.  0.  1.  0.5] -> NOT GO 
[1.   1.   1.   0.92] -> NOT GO 


WEEK3
